<a href="https://colab.research.google.com/github/jesse-venson/Machine-learning/blob/main/ML_Assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assign 1 - numpy

In [2]:
import numpy as np
#reverse an array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [4]:
#(b)flatten
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
# Method 1
flat1 = array1.flatten()
# Method 2
flat2 = array1.ravel()
print(flat1)

[1 2 3 2 4 5 1 2 3]


In [5]:
#(c)compare
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = np.array_equal(arr1, arr2)


In [8]:
#(d)most frequest indices
# i
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
unique, counts = np.unique(x, return_counts=True)
most_freq_val = unique[np.argmax(counts)]
indices = np.where(x == most_freq_val)
print(indices)
# ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_y, counts_y = np.unique(y, return_counts=True)
most_freq_y = unique_y[np.argmax(counts_y)]
indices_y = np.where(y == most_freq_y)
print(indices_y)

(array([0, 5, 7, 8]),)
(array([0, 1, 2]),)


In [10]:
#(e)matrix operations
gfg = np.matrix('4, 1, 9; 12, 3, 1; 4, 5, 6')
# i
sum_all = gfg.sum()
# ii
row_sum = gfg.sum(axis=1)
# iii
col_sum = gfg.sum(axis=0)
print(col_sum)

[[20  9 16]]


In [11]:
#(f)matrix computations
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
# i
diag_sum = np.trace(n_array)
# ii
eig_vals, eig_vecs = np.linalg.eig(n_array)
# iii
eig_vecs  # Already computed above
# iv
inverse = np.linalg.inv(n_array)
# v
det = np.linalg.det(n_array)


In [16]:
#(g) Matrix multiplication and covariance
import numpy as np

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5], [6, 7], [8, 9]])  # Adjusted to match p's shape

product2 = np.dot(p, q.T)
print("Product:\n", product2)

# Covariance: compare corresponding features (columns)
cov2 = np.cov(p.T, q.T)
print("Covariance between p and q:\n", cov2)


Product:
 [[14 20 26]
 [23 33 43]
 [41 59 77]]
Covariance between p and q:
 [[2.33333333 2.33333333 3.         3.        ]
 [2.33333333 2.33333333 3.         3.        ]
 [3.         3.         4.         4.        ]
 [3.         3.         4.         4.        ]]


In [19]:
#(h) Outer and Cartesian product
x = np.array([[1, 2, 3], [2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Outer product
outer = np.outer(x.flatten(), y.flatten())

# Cartesian product
from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print(cartesian)

[[ 1  1]
 [ 1  5]
 [ 1  0]
 [ 1  5]
 [ 1 10]
 [ 1  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [21]:
# 2-(a)
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)
print("Absolute values:\n", abs_array)

flat = array.flatten()
percentiles_flat = np.percentile(flat, [25, 50, 75])
print("Percentiles (flat):", percentiles_flat)

percentiles_cols = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles (columns):\n", percentiles_cols)

percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles (rows):\n", percentiles_rows)

mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)

print("Mean (flat):", mean_flat)
print("Median (flat):", median_flat)
print("Std Dev (flat):", std_flat)

mean_cols = np.mean(array, axis=0)
median_cols = np.median(array, axis=0)
std_cols = np.std(array, axis=0)

print("Mean (columns):", mean_cols)
print("Median (columns):", median_cols)
print("Std Dev (columns):", std_cols)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Mean (rows):", mean_rows)
print("Median (rows):", median_rows)
print("Std Dev (rows):", std_rows)



Absolute values:
 [[1 2 3]
 [4 5 6]]
Percentiles (flat): [-3.5 -0.5  2.5]
Percentiles (columns):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flat): -0.5
Median (flat): -0.5
Std Dev (flat): 3.8622100754188224
Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Std Dev (columns): [2.5 3.5 4.5]
Mean (rows): [ 0.66666667 -1.66666667]
Median (rows): [ 1. -4.]
Std Dev (rows): [2.05480467 4.78423336]


In [23]:
#2-(b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_vals = np.floor(a)
print("Floor:", floor_vals)
ceil_vals = np.ceil(a)
print("Ceiling:", ceil_vals)
trunc_vals = np.trunc(a)
print("Truncated:", trunc_vals)
rounded_vals = np.round(a)
print("Rounded:", rounded_vals)


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [24]:
#3-(a)
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

smallest_4 = np.sort(array)[:4]
print("4 smallest elements:", smallest_4)

largest_5 = np.sort(array)[-5:][::-1]  # Sorted in descending order
print("5 largest elements:", largest_5)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


In [25]:
#3-(b)
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array_b[array_b == array_b.astype(int)]
print("Integer elements only:", int_elements)

float_elements = array_b[array_b != array_b.astype(int)]
print("Float elements only:", float_elements)



Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [26]:
#4
import numpy as np
import cv2

def img_to_array(path):

    img_gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    if img_gray is not None:
        print("Grayscale image detected.")
        np.savetxt("grayscale_image.txt", img_gray, fmt='%d')
        print("Saved as 'grayscale_image.txt'")
        return img_gray
    else:
        # Read as RGB (BGR by default in OpenCV)
        img_rgb = cv2.imread(path, cv2.IMREAD_COLOR)
        if img_rgb is None:
            raise FileNotFoundError("Image not found or unreadable")

        # Convert BGR to RGB
        img_rgb = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB)
        print("RGB image detected.")

        # Save each channel separately
        np.savetxt("rgb_red.txt", img_rgb[:, :, 0], fmt='%d')
        np.savetxt("rgb_green.txt", img_rgb[:, :, 1], fmt='%d')
        np.savetxt("rgb_blue.txt", img_rgb[:, :, 2], fmt='%d')
        print("Saved as 'rgb_red.txt', 'rgb_green.txt', and 'rgb_blue.txt'")
        return img_rgb
